/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element, jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions */
"use client";

import { useState } from "react";

const factLabels: Record<string, string> = { SETTLEMENT_AMOUNT: "汇款结算金额", INVOICE_AMOUNT: "发票金额", PAYER_NAME: "付款人", BENEFICIARY_NAME: "收款人", BUYER_NAME: "买方", EXPORTER_NAME: "出口商" };
const factStatus: Record<string, string> = { VALIDATED: "已验证", CANDIDATE: "需确认", REJECTED: "未通过" };
const verificationLabels: Record<string, string> = { AMOUNT_MATCH: "金额一致性", ROLE_ALIGNED_PARTY_MATCH: "主体关系一致性" };
const verificationStatus: Record<string, string> = { PASS: "通过", UNCERTAIN: "需确认", FAIL: "未通过" };
const reasonCodeLabel: Record<string, string> = { VERIFICATION_AMOUNT_FAIL: "汇款金额与发票金额不一致", FACT_CRITICAL_CONFLICT: "存在关键事实冲突", FACT_REQUIRED_NOT_VALIDATED: "关键事实仍需人工确认", FACT_INPUT_MISSING: "关键事实输入缺失", MANUAL_REVIEW_REQUIRED: "需要人工复核", ACTOR_ROLE_NOT_ALLOWED: "当前角色无权执行此动作" };
const workflowLabel: Record<string, string> = { PRECHECK_PENDING: "待智能分析", PRECHECK_COMPLETE: "智能分析完成", READY_FOR_FAST_REVIEW: "待快速复核", READY_FOR_FOCUSED_REVIEW: "待重点复核", SUPPLEMENT_REQUIRED: "待客户补件" };
const valueText = (fact: any) => typeof fact?.normalizedValue === "object" ? `${fact.normalizedValue.currency ?? ""} ${Number(fact.normalizedValue.amount ?? 0).toLocaleString()}`.trim() : String(fact?.normalizedValue ?? fact?.rawValue ?? "—");
const shortHash = (value?: string) => value ? `${value.slice(0, 10)}…${value.slice(-8)}` : "—";

export function LiveDemoWorkspace({ role, session, onRole }: any) {
  const [selectedFact, setSelectedFact] = useState<any>(null);
  const [showPrinciple, setShowPrinciple] = useState(false);
  const [showChain, setShowChain] = useState(false);
  const summary = session.liveSummary;
  const currentCase = summary?.case;
  const run = summary?.currentAnalysisRun;
  const facts = summary?.facts ?? [];
  const evidence = summary?.evidence ?? [];
  const relations = summary?.relations ?? [];
  const verifications = summary?.verifications ?? [];
  const decisions = summary?.latestCavDecisions ?? [];
  const currentDecision = decisions.at(-1);
  const selectedEvidence = selectedFact ? evidence.filter((item: any) => selectedFact.evidenceRefs?.includes(item.evidenceId)) : [];
  const state = currentCase?.workflowState ?? "PRECHECK_PENDING";
  const chooseFile = async (event: any) => { const file = event.target.files?.[0]; if (!file) return; if (!/^image\/(jpeg|png)$/.test(file.type)) return; if (file.size > 15 * 1024 * 1024) return; await session.upload(file).catch(() => {}); };

  if (role === "customer") return <div className="stack live-workspace" data-live="true">
    <section className="page-intro"><div><span className="eyebrow red-eyebrow">LOCAL LIVE · 材料中心</span><h2>上传商业发票并启动真实智能分析</h2><p>文件将由本地 Demo Backend 保存、计算 SHA-256，并进入 RapidOCR、Laya、FACT 与一致性核验。</p></div><span className="status-pill blue">真实联调模式</span></section>
    <section className="live-upload-grid"><div className="panel live-upload-card"><h3>商业发票</h3><label className="upload21">选择 JPG / PNG<input type="file" accept="image/jpeg,image/png,.jpg,.jpeg,.png" onChange={chooseFile} /></label>{session.uploadedFile && <div className="live-file-meta"><b>{session.uploadedFile.name}</b><span>{session.uploadedFile.type} · {(session.uploadedFile.size / 1024).toFixed(1)} KB</span></div>}{session.demoCaseId && <Detail label="业务编号" value={session.demoCaseId} />}{session.uploadedDocument && <><Detail label="Document ID" value={session.uploadedDocument.documentId} /><Detail label="文件完整性校验 · SHA-256" value={shortHash(session.uploadedDocument.fileHash)} code /></>}{session.liveError && <div className="live-error">{session.liveError}</div>}<button className="primary wide" disabled={!session.uploadedDocument || Boolean(session.liveLoading)} onClick={() => session.analyze()}>{session.liveLoading === "analysis" ? "正在进行真实智能分析…" : summary?.currentAnalysisRun ? "重新分析" : "开始智能分析"}</button>{session.liveLoading === "analysis" && <div className="live-loading-steps"><span>正在读取商业发票</span><span>正在进行OCR识别</span><span>正在识别金额与交易主体</span><span>正在构建结构化业务事实</span><span>正在执行一致性核验</span></div>}{summary?.currentAnalysisRun && <button className="outline wide" onClick={() => onRole("operator")}>查看真实分析结果</button>}</div><div className="panel live-preview"><div><span>刚刚上传的原始单据</span><b>{session.uploadedFile?.name ?? "尚未选择文件"}</b></div>{session.uploadedPreviewUrl ? <img src={session.uploadedPreviewUrl} alt="用户上传的商业发票" /> : <div className="live-preview-empty">等待选择商业发票</div>}</div></section>
  </div>;

  if (role === "runtime") return <div className="stack live-workspace" data-live="true"><section className="runtime-final-title"><span>工银智汇通 · 可信作业运行监控</span><p>展示一笔国际汇款从材料进入到可信业务执行的完整技术过程。</p></section><div className="live-runtime-stages">
    <RuntimeStage no="01" title="汇款与材料接入"><Detail label="业务编号" value={session.demoCaseId ?? "—"} /><Detail label="PACS Document" value={summary?.documents?.find((x: any) => x.documentType === "PACS008")?.documentId ?? "—"} /><Detail label="Uploaded Invoice" value={session.uploadedDocument?.documentId ?? "—"} /><Detail label="SHA-256" value={shortHash(session.uploadedDocument?.fileHash)} code /></RuntimeStage>
    <RuntimeStage no="02" title="智能单据识别"><Detail label="RapidOCR" value={run ? "识别完成" : "等待执行"} /><Detail label="Laya" value={run ? "字段选择完成" : "等待执行"} /><Detail label="AnalysisRun ID" value={run?.analysisRunId ?? "—"} code /></RuntimeStage>
    <RuntimeStage no="03" title="结构化事实构建"><Detail label="Facts" value={String(facts.length)} /><Detail label="已验证" value={String(facts.filter((x: any) => x.factStatus === "VALIDATED").length)} /><Detail label="需确认" value={String(facts.filter((x: any) => x.factStatus === "CANDIDATE").length)} /></RuntimeStage>
    <RuntimeStage no="04" title="一致性核验"><Detail label="Verifications" value={String(verifications.length)} /><Detail label="金额一致性" value={verificationStatus[verifications.find((x: any) => x.checkType === "AMOUNT_MATCH")?.result] ?? "—"} /><Detail label="关键事实冲突" value={relations.some((x: any) => x.relationType === "CONFLICTS_WITH") ? "已发现" : "未发现"} /></RuntimeStage>
    <RuntimeStage no="05" title="可信执行决策"><Detail label="CavDecision ID" value={currentDecision?.cavDecisionId ?? "—"} code /><Detail label="Requested Action" value={currentDecision?.requestedAction ?? "—"} /><Detail label="Status" value={currentDecision?.status ?? "—"} /><Detail label="Policy" value={currentDecision?.policyVersion ?? "—"} /></RuntimeStage>
    <RuntimeStage no="06" title="业务状态流转"><Detail label="当前状态" value={`${workflowLabel[state] ?? state} · ${state}`} /><Detail label="WorkflowEvent" value={String(summary?.workflowEvents?.length ?? 0)} /><Detail label="AuditEvent" value={String(summary?.auditEvents?.length ?? 0)} /></RuntimeStage>
  </div><div className="runtime-secondary-actions"><button className="outline" onClick={() => setShowPrinciple(true)}>查看CAV技术原理</button><button className="outline" onClick={() => setShowChain(!showChain)}>{showChain ? "收起完整执行链" : "查看完整执行链"}</button></div>{showChain && <div className="panel live-full-chain">{["材料接入","文件Hash","PACS解析","RapidOCR","Laya选择","Evidence","FACT","FactRelation","Verification","AnalysisRun完成","CAV输入快照","CAV Policy","Decision绑定","Trusted Execution","FLOW Guard","WorkflowEvent","AuditEvent","状态刷新","经办视图","复核视图","运行监控"].map((x, i) => <span key={x}><b>{String(i + 1).padStart(2, "0")}</b>{x}</span>)}</div>}{showPrinciple && <div className="live-modal" onClick={() => setShowPrinciple(false)}><div className="live-modal-card" onClick={(e) => e.stopPropagation()}><button onClick={() => setShowPrinciple(false)}>×</button><span className="eyebrow red-eyebrow">CAV技术原理</span><h3>自动驾驶安全思想的银行可信执行迁移</h3><p>多源感知对应报文与单据接入；环境理解对应事实与一致性核验；安全控制器对应确定性CAV决策；驾驶员接管对应银行人工复核。</p><div className="mapping-line"><span>多源感知</span><b>→</b><span>事实融合</span><b>→</b><span>可信决策</span><b>→</b><span>人工接管</span></div></div></div>}</div>;

  return <div className="stack live-workspace" data-live="true"><section className="page-intro"><div><span className="eyebrow red-eyebrow">{role === "reviewer" ? "银行复核岗" : "银行经办岗"} · LOCAL LIVE</span><h2>{session.demoCaseId ?? "尚未创建真实业务"}</h2><p>当前状态：{workflowLabel[state] ?? state} <code>{state}</code></p></div><span className="status-pill amber">C03 · USD 153,000.00</span></section>
    {!summary?.currentAnalysisRun ? <section className="panel live-empty"><h3>尚无真实分析结果</h3><p>请先在企业端材料中心上传商业发票并完成智能分析。</p><button className="primary" onClick={() => onRole("customer")}>返回材料中心</button></section> : <div className="live-review-grid"><section className="panel"><h3>结构化业务事实（FACT）</h3><div className="live-fact-list">{facts.map((fact: any) => <button key={fact.factId} className={selectedFact?.factId === fact.factId ? "active" : ""} onClick={() => setSelectedFact(fact)}><span>{factLabels[fact.factType] ?? fact.factType}<small>{fact.factType}</small></span><b>{valueText(fact)}</b><em className={fact.factStatus.toLowerCase()}>{factStatus[fact.factStatus] ?? fact.factStatus}</em></button>)}</div>{selectedFact && <div className="live-evidence"><h4>对应证据</h4>{selectedEvidence.map((item: any) => <div key={item.evidenceId}><b>{item.documentId}</b><span>{item.sourceText}</span><code>{item.locator?.type} · Page {item.locator?.page ?? 1} · BBox {JSON.stringify(item.locator?.bbox ?? [])}</code><small>Source Hash {shortHash(item.sourceHash)}</small></div>)}</div>}</section><aside className="stack"><section className="panel"><h3>一致性核验</h3>{verifications.map((item: any) => <div className="live-verification" key={item.verificationId}><span>{verificationLabels[item.checkType] ?? item.checkType}<small>{item.checkType}</small></span><b className={item.result.toLowerCase()}>{verificationStatus[item.result] ?? item.result}</b></div>)}{relations.some((x: any) => x.relationType === "CONFLICTS_WITH") && <div className="live-conflict"><b>发现关键事实冲突</b><span>CONFLICTS_WITH</span></div>}</section><section className="panel live-cav"><h3>可信执行决策（CAV）</h3><button className="primary wide" disabled={Boolean(session.liveLoading)} onClick={() => session.act("ADVANCE_TO_FAST_REVIEW")}>申请快速复核</button>{(session.lastActionResult || currentDecision) && <ActionResult result={session.lastActionResult} decision={currentDecision} state={state} />}{currentDecision?.status === "BLOCK" && <><p>当前业务状态未因被阻止的动作而改变。</p><button className="outline wide" disabled={Boolean(session.liveLoading)} onClick={() => session.act("ADVANCE_TO_FOCUSED_REVIEW")}>进入重点复核</button><button className="ghost wide" disabled={Boolean(session.liveLoading)} onClick={() => session.act("REQUEST_SUPPLEMENT")}>要求客户补充材料</button></>}</section></aside></div>}
  </div>;
}

function Detail({ label, value, code = false }: any) { return <div className="live-detail"><span>{label}</span>{code ? <code>{value}</code> : <strong>{value}</strong>}</div>; }
function RuntimeStage({ no, title, children }: any) { return <section className="panel live-runtime-stage"><div><b>{no}</b><h3>{title}</h3></div>{children}</section>; }
function ActionResult({ result, decision, state }: any) { const status = decision?.status ?? result?.decision?.status ?? "—"; const reasons = decision?.reasonCodes ?? result?.decision?.reasonCodes ?? []; return <div className={`live-action-result ${String(status).toLowerCase()}`}><strong>{status === "BLOCK" ? "阻止当前动作" : status === "ALLOW" ? "允许执行" : "需要人工处理"}<small>{status}</small></strong><Detail label="申请动作" value={decision?.requestedAction ?? result?.decision?.requestedAction ?? "—"} /><Detail label="CavDecision ID" value={decision?.cavDecisionId ?? result?.decision?.cavDecisionId ?? "—"} code /><Detail label="Policy Version" value={decision?.policyVersion ?? result?.decision?.policyVersion ?? "—"} /><Detail label="AnalysisRun ID" value={decision?.analysisRunId ?? result?.decision?.analysisRunId ?? "—"} code /><Detail label="当前 FLOW State" value={state} />{reasons.map((code: string) => <p key={code}>{reasonCodeLabel[code] ?? code}<small>{code}</small></p>)}</div>; }
